apiVersion: v1
kind: Pod
metadata:
  name: my-app
space:
  containers:
    - name: app-container
      image: 164358940697.dkr.ecr.us-east-1.amazonaws.com/tomcat-repo:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8080