apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student
        image: 164358940697.dkr.ecr.us-east-1.amazonaws.com/tomcat-repo:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080